from __future__ import annotations

import tkinter as tk
from dataclasses import dataclass
from pathlib import Path
from tkinter import ttk
from typing import Final

from PIL import Image, ImageDraw, ImageOps, ImageTk
from PIL.Image import Image as PILImage

from utils import (
    LabAdjustment,
    LabColor,
    calculate_average_lab,
    lab_to_rgb_conversion,
    load_image,
    rgb_to_lab_conversion,
    save_image,
)

PREVIEW_IMAGE_SIZE: Final[tuple[int, int]] = (320, 320)
DEFAULT_IMAGE_PATH = Path("image/image.png")
ORIGINAL_PREVIEW_SAVE_PATH = Path("image/image-original-preview.png")
LAB_TIFF_SAVE_PATH = Path("image/image-lab-output.tiff")
LAB_ROUNDTRIP_PREVIEW_SAVE_PATH = Path("image/image-lab-to-rgb-preview.png")


@dataclass(frozen=True, slots=True)
class ConversionResult:
    """Hold the generated images used by the preview UI and output files."""

    original_rgb: PILImage
    lab_image: PILImage
    lab_roundtrip_rgb: PILImage


@dataclass(frozen=True, slots=True)
class SliderConfig:
    """Describe one LAB slider shown in the interface."""

    key: str
    label: str
    minimum: float
    maximum: float
    resolution: float = 1.0


SLIDER_CONFIGS: Final[tuple[SliderConfig, ...]] = (
    SliderConfig("l", "Lightness (L)", 0.0, 100.0, resolution=0.5),
    SliderConfig("a", "Green/Magenta (a)", -128.0, 127.0),
    SliderConfig("b", "Blue/Yellow (b)", -128.0, 127.0),
)


def main() -> None:
    source_image = load_image(resolve_image_path())
    conversion_result = build_conversion_result(source_image)
    save_conversion_outputs(conversion_result)
    LabPreviewApp(conversion_result).run()


def resolve_image_path() -> Path:
    """Resolve the default image path or generate a source image when it is missing."""
    if DEFAULT_IMAGE_PATH.exists():
        return DEFAULT_IMAGE_PATH

    generated_image_path = generate_default_image()
    print(f"Default image not found. Generated a new source image at {generated_image_path}")
    return generated_image_path


def generate_default_image() -> Path:
    """Generate a colorful source image so the transformations can still run."""
    DEFAULT_IMAGE_PATH.parent.mkdir(parents=True, exist_ok=True)

    width, height = 640, 640
    generated_image = Image.new("RGB", (width, height))
    pixels = generated_image.load()
    if pixels is None:
        raise ValueError("Unable to access pixel data for generated source image.")

    for y in range(height):
        for x in range(width):
            red = round((x / (width - 1)) * 255)
            green = round((y / (height - 1)) * 255)
            blue = round((((x + y) / 2) / ((width + height) / 2 - 1)) * 255)
            pixels[x, y] = (red, green, blue)

    draw = ImageDraw.Draw(generated_image)
    draw.ellipse((60, 60, 280, 280), outline=(255, 255, 255), width=10, fill=(255, 80, 80))
    draw.rectangle((360, 80, 580, 260), outline=(20, 20, 20), width=8, fill=(70, 180, 255))
    draw.polygon([(120, 500), (320, 320), (520, 500)], outline=(255, 255, 255), fill=(255, 220, 60))
    draw.line((40, 600, 600, 40), fill=(0, 0, 0), width=6)

    save_image(generated_image, DEFAULT_IMAGE_PATH)
    return DEFAULT_IMAGE_PATH


def build_conversion_result(img_object: PILImage) -> ConversionResult:
    """Create the RGB source image, LAB image, and RGB round-trip preview."""
    original_rgb = img_object.convert("RGB")
    lab_image = rgb_to_lab_conversion(original_rgb)
    lab_roundtrip_rgb = lab_to_rgb_conversion(lab_image)
    return ConversionResult(
        original_rgb=original_rgb,
        lab_image=lab_image,
        lab_roundtrip_rgb=lab_roundtrip_rgb,
    )


def save_conversion_outputs(conversion_result: ConversionResult) -> None:
    """Persist the core outputs generated by the LAB conversion pipeline."""
    LAB_TIFF_SAVE_PATH.parent.mkdir(parents=True, exist_ok=True)

    outputs = (
        ("Original RGB", conversion_result.original_rgb, ORIGINAL_PREVIEW_SAVE_PATH),
        ("LAB TIFF", conversion_result.lab_image, LAB_TIFF_SAVE_PATH),
        ("LAB -> RGB Preview", conversion_result.lab_roundtrip_rgb, LAB_ROUNDTRIP_PREVIEW_SAVE_PATH),
    )

    for title, img_object, save_path in outputs:
        save_image(img_object, save_path)
        print(f"{title} saved on {save_path}")


class LabPreviewApp:
    """Display the original image beside a live LAB-adjusted RGB preview."""

    def __init__(self, conversion_result: ConversionResult) -> None:
        self.conversion_result = conversion_result
        self.preview_original_rgb = _prepare_preview_image(conversion_result.original_rgb)
        self.preview_lab_image = rgb_to_lab_conversion(self.preview_original_rgb)
        self.base_lab_color: LabColor = calculate_average_lab(self.preview_lab_image)

        self.root = tk.Tk()
        self.root.title("LAB Round-Trip Preview")

        self.slider_vars: dict[str, tk.DoubleVar] = {
            config.key: tk.DoubleVar(
                master=self.root,
                value=self._initial_slider_value(config),
            )
            for config in SLIDER_CONFIGS
        }
        self.slider_value_labels: dict[str, ttk.Label] = {}

        self.original_photo_image = ImageTk.PhotoImage(self.preview_original_rgb)
        self.adjusted_photo_image: ImageTk.PhotoImage | None = None
        self.adjusted_image_label: ttk.Label | None = None
        self.adjustment_summary_label: ttk.Label | None = None

        self._build_window()
        self._refresh_adjusted_preview()

    def run(self) -> None:
        """Start the Tkinter preview loop."""
        self.root.mainloop()

    def _build_window(self) -> None:
        container = ttk.Frame(self.root, padding=16)
        container.grid(sticky="nsew")

        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(0, weight=1)
        container.columnconfigure(0, weight=1)
        container.rowconfigure(0, weight=1)

        preview_frame = ttk.Frame(container)
        preview_frame.grid(row=0, column=0, sticky="nsew")
        preview_frame.columnconfigure(0, weight=1)
        preview_frame.columnconfigure(1, weight=1)

        self._build_original_panel(preview_frame)
        self._build_adjusted_panel(preview_frame)
        self._build_slider_panel(container)

    def _build_original_panel(self, parent: ttk.Frame) -> None:
        frame = ttk.LabelFrame(parent, text="Original RGB", padding=12)
        frame.grid(row=0, column=0, padx=(0, 8), pady=(0, 16), sticky="nsew")

        image_label = ttk.Label(frame, image=self.original_photo_image)
        image_label.grid(row=0, column=0)

    def _build_adjusted_panel(self, parent: ttk.Frame) -> None:
        frame = ttk.LabelFrame(parent, text="LAB -> RGB Preview", padding=12)
        frame.grid(row=0, column=1, padx=(8, 0), pady=(0, 16), sticky="nsew")

        self.adjusted_image_label = ttk.Label(frame)
        self.adjusted_image_label.grid(row=0, column=0)

        self.adjustment_summary_label = ttk.Label(frame, padding=(0, 10, 0, 0))
        self.adjustment_summary_label.grid(row=1, column=0)

    def _build_slider_panel(self, parent: ttk.Frame) -> None:
        frame = ttk.LabelFrame(parent, text="LAB Controls", padding=12)
        frame.grid(row=1, column=0, sticky="ew")
        frame.columnconfigure(1, weight=1)

        helper_label = ttk.Label(
            frame,
            text="The sliders start from the average LAB values computed from the RGB to LAB conversion.",
            wraplength=700,
        )
        helper_label.grid(row=0, column=0, columnspan=3, sticky="w", pady=(0, 12))

        for row, config in enumerate(SLIDER_CONFIGS, start=1):
            label = ttk.Label(frame, text=config.label)
            label.grid(row=row, column=0, sticky="w", padx=(0, 12), pady=4)

            slider = tk.Scale(
                frame,
                from_=config.minimum,
                to=config.maximum,
                resolution=config.resolution,
                orient=tk.HORIZONTAL,
                length=340,
                variable=self.slider_vars[config.key],
                command=self._handle_slider_change,
            )
            slider.grid(row=row, column=1, sticky="ew", pady=4)

            value_label = ttk.Label(frame, width=8, anchor="e")
            value_label.grid(row=row, column=2, sticky="e", pady=4)
            self.slider_value_labels[config.key] = value_label

        reset_button = ttk.Button(
            frame,
            text="Reset to Default",
            command=self._reset_to_default_values,
        )
        reset_button.grid(row=len(SLIDER_CONFIGS) + 1, column=0, columnspan=3, sticky="e", pady=(12, 0))

    def _handle_slider_change(self, _value: str) -> None:
        self._refresh_adjusted_preview()

    def _reset_to_default_values(self) -> None:
        for config in SLIDER_CONFIGS:
            self.slider_vars[config.key].set(self._initial_slider_value(config))
        self._refresh_adjusted_preview()

    def _refresh_adjusted_preview(self) -> None:
        current_lab_color = self._current_lab_color()
        adjustment = self._current_adjustment(current_lab_color)
        adjusted_rgb = lab_to_rgb_conversion(self.preview_lab_image, adjustment)

        self.adjusted_photo_image = ImageTk.PhotoImage(adjusted_rgb)
        if self.adjusted_image_label is not None:
            self.adjusted_image_label.configure(image=self.adjusted_photo_image)

        if self.adjustment_summary_label is not None:
            self.adjustment_summary_label.configure(
                text=(
                    "Average LAB target: "
                    f"L { _format_channel_value(current_lab_color.lightness) } | "
                    f"a { _format_channel_value(current_lab_color.a_value) } | "
                    f"b { _format_channel_value(current_lab_color.b_value) }"
                )
            )

        for config in SLIDER_CONFIGS:
            self.slider_value_labels[config.key].configure(
                text=_format_channel_value(self.slider_vars[config.key].get())
            )

    def _current_adjustment(self, current_lab_color: LabColor) -> LabAdjustment:
        return LabAdjustment(
            lightness_delta=current_lab_color.lightness - self.base_lab_color.lightness,
            a_delta=current_lab_color.a_value - self.base_lab_color.a_value,
            b_delta=current_lab_color.b_value - self.base_lab_color.b_value,
        )

    def _initial_slider_value(self, config: SliderConfig) -> float:
        base_values = {
            "l": self.base_lab_color.lightness,
            "a": self.base_lab_color.a_value,
            "b": self.base_lab_color.b_value,
        }
        return base_values[config.key]

    def _current_lab_color(self) -> LabColor:
        return LabColor(
            lightness=self.slider_vars["l"].get(),
            a_value=self.slider_vars["a"].get(),
            b_value=self.slider_vars["b"].get(),
        )


def _prepare_preview_image(img_object: PILImage) -> PILImage:
    """Convert the image into a Tkinter-friendly preview size."""
    preview_image = img_object.convert("RGB")
    return ImageOps.contain(preview_image, PREVIEW_IMAGE_SIZE)


def _format_channel_value(value: float) -> str:
    """Format LAB channel values consistently for the live labels."""
    if value.is_integer():
        return f"{value:.0f}"
    return f"{value:.1f}"


if __name__ == "__main__":
    main()
